### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#11]
This server has memory leak as original Ogar. Anybody have any ideas how to deal with this??( It's f*cking crazy. Language with garbage collector and memory leaks...

**Comment by Barbosik** [comment]
how did you noticed that there is memory leak?
May be it's just some non-effective bot algorithms which consumes a lot of memory?
Did you tested it with no bots?

**Comment by F0RIS** [comment]
@Barbosik i have vps with 2GB RAM. And after some time nodejs process eat all memory. I don't use bots at all 
![default](https://cloud.githubusercontent.com/assets/10178982/15833124/f2aa43a6-2c2d-11e6-86eb-56ba208b60c1.png)

**Comment by Barbosik** [comment]
I tested it for a little, and it seems like truth, it consumes 100 megabytes in the first 5-10 minutes (it's normal for GC, at this time it adapts to the application behavior).
But then memory consumption grows with a small speed, it looks like real memory leak.

May be update node.js to the latest version will helps. Did you tested it?

**Comment by F0RIS** [comment]
Tested 4.4.3, 4.4.4, and 0.10.25 (default version from reps, dunno why so strange nubmers, but it's equal around 4.4.3). New 6+ versions didn't try. Sometimes it stop leaking at some point and work for a long time, but it's rare behavior. Here part of my log . From it you can see how often linux kernel killing nodejs process. And this is with 2GB RAM....sadly.
05 Jun 16 16:37:  Nodejs was killed, restarting..
05 Jun 16 17:18:  Nodejs was killed, restarting..
05 Jun 16 18:17:  Nodejs was killed, restarting..
05 Jun 16 20:50:  Nodejs was killed, restarting..
05 Jun 16 21:34:  Nodejs was killed, restarting..
05 Jun 16 22:28:  Nodejs was killed, restarting..
05 Jun 16 23:19:  Nodejs was killed, restarting..
06 Jun 16 00:26:  Nodejs was killed, restarting..
06 Jun 16 02:14:  Nodejs was killed, restarting..
06 Jun 16 03:17:  Nodejs was killed, restarting..
06 Jun 16 16:12:  Nodejs was killed, restarting..
06 Jun 16 18:25:  Nodejs was killed, restarting..
06 Jun 16 19:11:  Nodejs was killed, restarting..
06 Jun 16 20:22:  Nodejs was killed, restarting..
06 Jun 16 21:45:  Nodejs was killed, restarting..

**Comment by Barbosik** [comment]
I read that 6+ version has some improvements in memory management. I added support for v6 in MultiOgar, it will be enabled automatically if it runs on v6+. But I didn't tested it :)

**Comment by F0RIS** [comment]
ok, i'll test 6+ version)

**Comment by F0RIS** [comment]
Nodejs v6.2.1
After few hours
![image](https://cloud.githubusercontent.com/assets/10178982/15905260/eafd3dda-2dbc-11e6-9df5-ce3cbe502e59.png)

**Comment by Barbosik** [comment]
I will try to minimize memory allocations later, it should help

**Comment by Barbosik** [comment]
If you're using it for commercial purposes. Just contact me with gmail: debug.debugov ;)
We can cooperate, I can make highly optimized server, written in C# with no memory leaks and with high speed.

This project is just for fun and to learn node.js :)

**Comment by Barbosik** [comment]
try the latest version. I fixed buffer allocation. Just missed some details from documentation.
I'm not sure that it's the real reason of memory leak, but may be it will help

**Comment by F0RIS** [comment]
Uptime 3 hours. Don't know better this than was or not but leak is still exist.
![image](https://cloud.githubusercontent.com/assets/10178982/15945093/59ff5772-2e99-11e6-9ce6-30080ac3150e.png)
Did you read this?  https://github.com/OgarProject/Ogar/issues/202

**Comment by Barbosik** [comment]
try the latest version, I added some optimizations in order to minimize memory allocations

**Comment by F0RIS** [comment]
it become better but still leaking(

**Comment by Barbosik** [comment]
yes, I see some small leaks still exists, have no idea what is the source. I will try to find it later

**Comment by Barbosik** [comment]
I think it's fixed now :)

Let me know if you catch memory leak again

**Comment by Barbosik** [comment]
just tested it for 1 hour with 100 bots and 1 client - no memory leaks at all

**Comment by Mistik** [comment]
> If you're using it for commercial purposes. Just contact me with gmail: debug.debugov ;) We can cooperate, I can make highly optimized server, written in C# with no memory leaks and with high speed.
> 
> This project is just for fun and to learn node.js :)

Emailed you

**Comment by F0RIS** [comment]
@Barbosik I dont recommend you having anything with this asshole Mistik, he has so bad reputation in io community😄
